HPCC-27773 - Create confidence tests and key files for the General Neural Network bundle
hpcc-systems/GNN pull request #7
Opened 2022-06-17 17:39 UTC by NSel1727

- Create ecl and key folder
- Develop test code to create confidence tests calling functions from the General Neural Network bundle
- Create a key file for each test, displaying the passing output in XML format

2022-06-22 16:03 UTC, NSel1727 commented
@AttilaVamos @ghalliday Please review my pull request

2022-06-27 17:17 UTC, NSel1727 commented
The ClassicTestModified file may only pass depending on the versions

Here are my versions (passes that test)

Python: 3.8.1
TensorFlow: 2.9.1
HPCC Platform: 8.6

2022-06-28 17:28 UTC, AttilaVamos requested changes
Generally and automated testing point of view it seems ok, but there is a question and some requests.

2022-06-28 17:28 UTC, AttilaVamos commented on ecl/!SetupTestOBT.ecl
> +            return [(nodeId, 'unknown', tb.format_exc())]
I think we know the reason of this exception. The message can be ' Failed to import tensorflow. Is it installed?' or something better to inform us about the problem.

2022-06-28 17:28 UTC, AttilaVamos commented on ecl/ClassicTestModified.ecl
> +HighErrors := COUNT(Errors(err > 0.1));
That's what we are talked yesterday. On my Ubuntu 18.04 + Tensorflow 2.6.2 this check (> 0.1) results > 200 errors.
If I change it to 0.2 then I can get only a couple of errors, and with 0.3 it is passed,
So, the question is 0.3 limit is acceptable for Tensor flow 2.9.1 or not?
If the answer is yes, we can use 0.3 for that check. 
If not, then I should ensure it is always executed on >=2.9.1. 
Or we can use stored parameter to input Tensor flow version (the automated test system can query it and pass forward) and set the limit value based on the stored parameter.

2022-06-28 17:28 UTC, AttilaVamos commented on eclcc.log
> +00000000 PRG 2022-06-28 12:52:16.183 11478 11478 "Loading plugin /opt/HPCCSystems/plugins/libunicodelib.so[lib_unicodelib] version = UNICODELIB 1.1.06"
Please remove this file.

2022-06-30 16:20 UTC, NSel1727 commented
@ghalliday @RogerDev When available, please review my pull request.

2022-07-12 17:15 UTC, lilyclemson commented
@NSel1727   To avoid confusion with GNN bundle's ECL files, please create a top level folder such as ConfTest to include the newly added folders/files. Thanks.  

@RogerDev

2022-07-13 16:13 UTC, NSel1727 commented
@lilyclemson A new root directory was added for the ecl folder to avoid confusion.

2022-07-15 15:52 UTC, AttilaVamos requested changes

2022-07-15 15:52 UTC, AttilaVamos commented on OBTTests/ecl/key/ClassicTestModified.xml
> + <Info><Source>user</Source><Message>Training Status: ModelId = 0, Epoch = 1, LR = 1.0, bs = 1024, Loss = 0.00142032571460249</Message></Info>
Please remove these '<Info>...</Info>' lines from the key file. The Regression Test Engine filters them out.

2022-07-19 17:29 UTC, lilyclemson commented
It's ready to merge. Please review. Thank you @ghalliday 


CC @RogerDev

2022-07-20 07:48 UTC, merged